config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :employments
  resources :details
  root to: 'details#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/detail.rb
# frozen_string_literal: true

class Detail < ApplicationRecord
  validates :first_name, presence: true, length: { maximum: 25 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :email_address, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :phone_number, presence: true
end

app/models/employment.rb
# frozen_string_literal: true

class Employment < ApplicationRecord
  validates :employer, :start_date, :end_date, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordInvalid do |e|
    render json: { errors: e.record.errors }, status: :unprocessable_entity
  end

  rescue_from ActiveRecord::RecordNotFound do |e|
    render json: { errors: e.record.errors }, status: :unprocessable_entity
  end

  rescue_from ActiveRecord::RecordNotUnique do |e|
    render json: { errors: e.record.errors }, status: :dublicate_entity
  end

  rescue_from ActiveRecord::RecordNotSaved do |e|
    render json: { errors: e.record.errors }, status: :unprocessable_entity
  end
end

app/controllers/details_controller.rb
# frozen_string_literal: true

class DetailsController < ApplicationController
  before_action :set_detail, only: %i[show edit update destroy]

  # GET /details or /details.json
  def index
    @details = Detail.all
    @employments = Employment.all
  end

  # GET /details/1 or /details/1.json
  def show; end

  # GET /details/new
  def new
    @detail = Detail.new
  end

  # GET /details/1/edit
  def edit; end

  # POST /details or /details.json
  def create
    @detail = Detail.new(detail_params)

    respond_to do |format|
      if @detail.save
        format.html { redirect_to new_employment_path }
        # format.turbo_stream do
        #   render turbo_stream: turbo_stream.prepend('details', partial: 'details/detail',
        #                                                        locals: { detail: @detail })
        # end

        format.json { render :show, status: :created, location: @detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /details/1 or /details/1.json
  def update
    respond_to do |format|
      if @detail.update(detail_params)
        format.html { redirect_to detail_url(@detail), notice: 'Detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /details/1 or /details/1.json
  def destroy
    respond_to do |format|
      if @detail.destroy
        format.html { redirect_to details_url }
        format.json { head :no_content }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_detail
    @detail = Detail.find(params[:id])
  end

  def set_employment
    @employment = Employment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def detail_params
    params.require(:detail).permit(:first_name, :last_name, :nick_name, :email_address, :phone_number)
  end
end

app/controllers/employments_controller.rb
# frozen_string_literal: true

class EmploymentsController < ApplicationController
  before_action :set_employment, only: %i[show edit update destroy]

  # GET /employments or /employments.json
  def index
    @employments = Employment.all
  end

  # GET /employments/1 or /employments/1.json
  def show; end

  # GET /employments/new
  def new
    @employment = Employment.new
  end

  # GET /employments/1/edit
  def edit; end

  # POST /employments or /employments.json
  def create
    @employment = Employment.new(employment_params)
    respond_to do |format|
      if @employment.save
        # format.turbo_stream do
        #   render turbo_stream: turbo_stream.append('details',
        #                                            partial: 'employments/employment',
        #                                            locals: { employment: @employment })
        # end
        format.html { redirect_to details_url(@employment) }
        format.json { render :show, status: :created, location: @employment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employments/1 or /employments/1.json
  def update
    respond_to do |format|
      if @employment.update(employment_params)
        format.html { redirect_to employment_url(@employment), notice: 'Employment was successfully updated.' }
        format.json { render :show, status: :ok, location: @employment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employments/1 or /employments/1.json
  def destroy
    respond_to do |format|
      if @employment.destroy
        format.html { redirect_to details_url }
        format.json { head :no_content }
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @detail.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employment
    @employment = Employment.find(params[:id])
  end

  def set_detail
    @detail = Detail.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def employment_params
    params.require(:employment).permit(:employer, :start_date, :end_date)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @details = Detail.all
  end

  def set_detail
    @detail = Detail.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/details_helper.rb
# frozen_string_literal: true

module DetailsHelper
end

app/helpers/employments_helper.rb
# frozen_string_literal: true

module EmploymentsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/details/_detail.html.slim
.p-6.max-w-sm.bg-white.rounded-lg.border.border-gray-200.shadow-md.dark:bg-gray-800.dark:border-gray-700
  |  <div id="
  = dom_id detail
  | "> 
  p
    strong
      | first_name:
    = detail.first_name
  p
    strong
      | last_name:
    = detail.last_name
  p
    strong
      | nick_name:
    = detail.nick_name
  p
    strong
      | email_address:
    = detail.email_address
  p
    strong
      | phone_number:
    = number_to_phone(detail.phone_number)

app/views/details/_form.html.slim
= form_with(model: detail) do |form|
  br
  div
    = form.label :first_name, style: "display: block", class: "block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
    = form.text_field :first_name, style: 'border: 2px solid #555;', required: true, maxlength: 25, size: 20
  br
  div
    = form.label :last_name, style: "display: block"
    = form.text_field :last_name, style: 'border: 2px solid #555;', required: true, maxlength: 50, size: 20
  br
  div
    = form.label :nick_name, style: "display: block"
    = form.text_field :nick_name, style: 'border: 2px solid #555;', placeholder: "optional"
  br
  div
    = form.label :email_address, style: "display: block"
    = form.email_field :email_address, style: 'border: 2px solid #555;', required: true, placeholder: "name@example.com"
  br
  div
    = form.label :phone_number, style: "display: block"
    = form.telephone_field :phone_number, style: 'border: 2px solid #555;', required: true, placeholder: "1111111111"
  br
  div
    = form.submit :class => "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"

app/views/details/edit.html.slim
h1
  | Editing detail
= render "form", detail: @detail
br
div
  = link_to "Show this detail", @detail
  |  | 
  = link_to "Back to details", details_path

app/views/details/index.html.slim
p[style="color: green"]
  = notice
br
br
= link_to "New details", new_detail_path, data:{turbo_frame: "modal", class: "rounded-lg"}, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
= link_to "New employment", new_employment_path, data:{turbo_frame: "modal", class: "rounded-lg"}, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
br
br
.flex.justify-center
  br
  div
    h1.text-3xl.font-bold.underline
      | Details
    br
    #details
      - @details.each do |detail|
        = render detail
        br
        p
          = link_to "Show this detail", detail, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded"
        br
  br
  div
    h1.text-3xl.font-bold
      | Employments
    br
    #employments
      - @employments.each do |employment|
        = render employment
        br
        p
          = link_to "Show this employment", employment, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded"
        br
br

app/views/details/new.html.slim
= turbo_frame_tag :modal do
  div[data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd"]
    h1
      | New detail
    = render "form", detail: @detail
    br
    div
      = link_to "Back to details", details_path

app/views/details/show.html.slim
p[style="color: green"]
  = notice
= render @detail
div
  = link_to "Edit this detail", edit_detail_path(@detail)
  |  | 
  = link_to "Back to details", details_path
  = button_to "Destroy this detail", @detail, method: :delete

app/views/employments/_employment.html.slim
.p-6.max-w-sm.bg-white.rounded-lg.border.border-gray-200.shadow-md.dark:bg-gray-800.dark:border-gray-700
  |  <div id="
  = dom_id employment
  | "> 
  p
    strong
      | employer:
    = employment.employer
  p
    strong
      | start_date:
    = employment.start_date
  p
    strong
      | end_date:
    = employment.end_date

app/views/employments/_form.html.slim
= form_with(model: employment) do |form|
  div
    = form.label :employer, style: "display: block"
    = form.text_field :employer, style: 'border: 2px solid #555;', required: true, placeholder: "employer Name"
  br
  div
    = form.label :start_date, style: "display: block"
    = form.datetime_field :start_date, style: 'border: 2px solid #555;', required: true
  br
  div
    = form.label :end_date, style: "display: block"
    = form.datetime_field :end_date, style: 'border: 2px solid #555;', required: true
  br
  div
    = form.submit :class => "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"

app/views/employments/_form_modal.html.slim
= turbo_frame_tag :remote_modal, target: :_top do
  #exampleModal.modal.fade.fixed.top-0.left-0.hidden.w-full.h-full.outline-none.overflow-x-hidden.overflow-y-auto[data-controller="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true"]
    .modal-dialog.relative.w-auto.pointer-events-none
      .modal-content.border-none.shadow-lg.relative.flex.flex-col.w-full.pointer-events-auto.bg-white.bg-clip-padding.rounded-md.outline-none.text-current
        .modal-header.flex.flex-shrink-0.items-center.justify-between.p-4.border-b.border-gray-200.rounded-t-md
          h5#exampleModalLabel.text-xl.font-medium.leading-normal.text-gray-800
            | Modal title
          button.btn-close.box-content.w-4.h-4.p-1.text-black.border-none.rounded-none.opacity-50.focus:shadow-none.focus:outline-none.focus:opacity-100.hover:text-black.hover:opacity-75.hover:no-underline[type="button" data-bs-dismiss="modal" aria-label="Close"]
        .modal-body.relative.p-4
          = render "form", employment: @employment
        .modal-footer.flex.flex-shrink-0.flex-wrap.items-center.justify-end.p-4.border-t.border-gray-200.rounded-b-md
          button.px-6.py-2.5.bg-purple-600.text-white.font-medium.text-xs.leading-tight.uppercase.rounded.shadow-md.hover:bg-purple-700.hover:shadow-lg.focus:bg-purple-700.focus:shadow-lg.focus:outline-none.focus:ring-0.active:bg-purple-800.active:shadow-lg.transition.duration-150.ease-in-out[type="button" data-bs-dismiss="modal"]
            | Close
          button.px-6.py-2.5.bg-blue-600.text-white.font-medium.text-xs.leading-tight.uppercase.rounded.shadow-md.hover:bg-blue-700.hover:shadow-lg.focus:bg-blue-700.focus:shadow-lg.focus:outline-none.focus:ring-0.active:bg-blue-800.active:shadow-lg.transition.duration-150.ease-in-out.ml-1[type="button"]
            | Save changes

app/views/employments/edit.html.slim
h1
  | Editing employment
= render "form", employment: @employment
br
div
  = link_to "Show this employment", @employment
  |  | 
  = link_to "Back to employments", details_path

app/views/employments/index.html.slim
p[style="color: green"]
  = notice
h1
  | Employments
#employments
  - @employments.each do |employment|
    = render employment
    p
      = link_to "Show this employment", employment
= link_to "New employment", new_employment_path

app/views/employments/new.html.slim
= turbo_frame_tag :modal do
  div[data-controller="turbomodal" data-action="turbo:submit-end->turbomodal#submitEnd"]
    h1
      | New employment
    = render "form", employment: @employment
    br
    div
      = link_to "Back to details", details_path

app/views/employments/show.html.slim
p[style="color: green"]
  = notice
= render @employment
div
  = link_to "Edit this employment", edit_employment_path(@employment)
  |  | 
  = link_to "Back to employments", details_path
  = button_to "Destroy this employment", @employment, method: :delete

app/views/home/index.html.slim
h1.text-3xl.font-bold
  |  Home Page 

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TestApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "tailwind", "data-turbo-track": "reload"
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_tag 'application'
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body
    = turbo_frame_tag :modal
    = yield